//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionarioApp {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("concesionarioApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Modelos.
        /// </summary>
        internal static string agregarModelos {
            get {
                return ResourceManager.GetString("agregarModelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alquiler coches.
        /// </summary>
        internal static string alquilerCoches {
            get {
                return ResourceManager.GetString("alquilerCoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar en Alquiler.
        /// </summary>
        internal static string AlquilerRadioButton {
            get {
                return ResourceManager.GetString("AlquilerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Coche.
        /// </summary>
        internal static string anadirCoche {
            get {
                return ResourceManager.GetString("anadirCoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coche.
        /// </summary>
        internal static string coche {
            get {
                return ResourceManager.GetString("coche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        internal static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compras.
        /// </summary>
        internal static string comprasRd {
            get {
                return ResourceManager.GetString("comprasRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Coches.
        /// </summary>
        internal static string comprobarCoches {
            get {
                return ResourceManager.GetString("comprobarCoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcion.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad.
        /// </summary>
        internal static string disponiblesRd {
            get {
                return ResourceManager.GetString("disponiblesRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eliminar.
        /// </summary>
        internal static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a enAlquiler.
        /// </summary>
        internal static string enAlquiler {
            get {
                return ResourceManager.GetString("enAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a enTaller.
        /// </summary>
        internal static string enTaller {
            get {
                return ResourceManager.GetString("enTaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a enVenta.
        /// </summary>
        internal static string enVenta {
            get {
                return ResourceManager.GetString("enVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el campo de apellidos.
        /// </summary>
        internal static string errorApellidos {
            get {
                return ResourceManager.GetString("errorApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el Color seleccionado.
        /// </summary>
        internal static string errorColor {
            get {
                return ResourceManager.GetString("errorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise la descripcion introducida.
        /// </summary>
        internal static string errorDescripcion {
            get {
                return ResourceManager.GetString("errorDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el email.
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores en el formulario.
        /// </summary>
        internal static string erroresFormulario {
            get {
                return ResourceManager.GetString("erroresFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el Estado seleccionado.
        /// </summary>
        internal static string errorEstado {
            get {
                return ResourceManager.GetString("errorEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise la fecha de nacimiento.
        /// </summary>
        internal static string errorFechaNacimiento {
            get {
                return ResourceManager.GetString("errorFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise la imagen introducida.
        /// </summary>
        internal static string errorImagenes {
            get {
                return ResourceManager.GetString("errorImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise Marca elegida.
        /// </summary>
        internal static string errorMarca {
            get {
                return ResourceManager.GetString("errorMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise la matricula.
        /// </summary>
        internal static string errorMatricula {
            get {
                return ResourceManager.GetString("errorMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el modelo elegido.
        /// </summary>
        internal static string errorModelo {
            get {
                return ResourceManager.GetString("errorModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el campo de nombre.
        /// </summary>
        internal static string errorNombre {
            get {
                return ResourceManager.GetString("errorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el campo de contraseña.
        /// </summary>
        internal static string errorPassword {
            get {
                return ResourceManager.GetString("errorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el Precio de alquiler.
        /// </summary>
        internal static string errorPrecioAlquiler {
            get {
                return ResourceManager.GetString("errorPrecioAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el Precio de Compra.
        /// </summary>
        internal static string errorPrecioCompra {
            get {
                return ResourceManager.GetString("errorPrecioCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el puesto.
        /// </summary>
        internal static string errorPuesto {
            get {
                return ResourceManager.GetString("errorPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el telefono.
        /// </summary>
        internal static string errorTelefono {
            get {
                return ResourceManager.GetString("errorTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise el campo de usuarios.
        /// </summary>
        internal static string errorUsuario {
            get {
                return ResourceManager.GetString("errorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperendo mecanico.
        /// </summary>
        internal static string esperarValidacionRd {
            get {
                return ResourceManager.GetString("esperarValidacionRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaCita.
        /// </summary>
        internal static string fechaCita {
            get {
                return ResourceManager.GetString("fechaCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaSolicitud.
        /// </summary>
        internal static string fechaSolicitud {
            get {
                return ResourceManager.GetString("fechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Situacion coches.
        /// </summary>
        internal static string graficaGeneral {
            get {
                return ResourceManager.GetString("graficaGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a imagenes.
        /// </summary>
        internal static string imagenes {
            get {
                return ResourceManager.GetString("imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a marca.
        /// </summary>
        internal static string marca {
            get {
                return ResourceManager.GetString("marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Marcas.
        /// </summary>
        internal static string marcasRd {
            get {
                return ResourceManager.GetString("marcasRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula.
        /// </summary>
        internal static string matricula {
            get {
                return ResourceManager.GetString("matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mecanico.
        /// </summary>
        internal static string mecanico {
            get {
                return ResourceManager.GetString("mecanico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        internal static string modelo {
            get {
                return ResourceManager.GetString("modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        internal static string motivo {
            get {
                return ResourceManager.GetString("motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No resuelto.
        /// </summary>
        internal static string noResuletasRd {
            get {
                return ResourceManager.GetString("noResuletasRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string NuevosButton {
            get {
                return ResourceManager.GetString("NuevosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a precio.
        /// </summary>
        internal static string precio {
            get {
                return ResourceManager.GetString("precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a precioAlquiler.
        /// </summary>
        internal static string precioAlquiler {
            get {
                return ResourceManager.GetString("precioAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a precioCompra.
        /// </summary>
        internal static string precioCompra {
            get {
                return ResourceManager.GetString("precioCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a propietario.
        /// </summary>
        internal static string propietario {
            get {
                return ResourceManager.GetString("propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        internal static string puesto {
            get {
                return ResourceManager.GetString("puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resueltas.
        /// </summary>
        internal static string resueltasRd {
            get {
                return ResourceManager.GetString("resueltasRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a resuelto.
        /// </summary>
        internal static string resuelto {
            get {
                return ResourceManager.GetString("resuelto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taller coche.
        /// </summary>
        internal static string tallerCoches {
            get {
                return ResourceManager.GetString("tallerCoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar en Taller.
        /// </summary>
        internal static string TallerRadioButton {
            get {
                return ResourceManager.GetString("TallerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TituloModelos.
        /// </summary>
        internal static string TituloModelos {
            get {
                return ResourceManager.GetString("TituloModelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar todos.
        /// </summary>
        internal static string TodosRadioButton {
            get {
                return ResourceManager.GetString("TodosRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas de Coche.
        /// </summary>
        internal static string ventasCoche {
            get {
                return ResourceManager.GetString("ventasCoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar en Venta.
        /// </summary>
        internal static string VentasRadioButton {
            get {
                return ResourceManager.GetString("VentasRadioButton", resourceCulture);
            }
        }
    }
}
